version: "3.9"

services:

  steedos:
    image: steedos/steedos-community:2.7.2-beta.1
    ports:
      - "5000:5000"    # Steedos
      - "27017:27017"  # MongoDB
      - "9001:9001"    # Supervisor
      - "6379:6379"    # Redis
    env_file:
      - .env
      - .env.local
    volumes:
      - "./steedos-storage:/steedos-storage"
      - "../public:/app/public"
    networks:
      - steedos_network

networks:
  steedos_network:
    driver: bridge